FROM ubuntu:18.04

ENV ANDROID_NDK_HOME /opt/android-ndk
ENV ANDROID_NDK_VERSION r21d
ENV DEBIAN_FRONTEND noninteractive



# ------------------------------------------------------
# --- Install required tools

RUN apt-get update -qq && \
    apt install -y openjdk-8-jdk  bash wget unzip make file git g++ build-essential curl wget && \
     wget https://cmake.org/files/v3.13/cmake-3.13.0.tar.gz && \
     tar -zxvf cmake-3.13.0.tar.gz && \
     cd cmake-3.13.0 && \
     ./configure && \
     make && \
     make install && \
     cmake --version && \
     cd .. && \
     rm cmake-3.13.0.tar.gz && \
     rm -rf cmake-3.13.0 && \
     apt-get clean


# ------------------------------------------------------
# --- Android NDK

# download
RUN mkdir /opt/android-ndk-tmp && \
    cd /opt/android-ndk-tmp && \
    wget -q https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip && \
# uncompress
    unzip -q android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip && \
# move to its final location
    mv ./android-ndk-${ANDROID_NDK_VERSION} ${ANDROID_NDK_HOME} && \
# remove temp dir
    cd ${ANDROID_NDK_HOME} && \
    rm -rf /opt/android-ndk-tmp

# add to PATH
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
ENV PATH $PATH:$JAVA_HOME/bin
ENV PATH $PATH:$ANDROID_NDK_HOME


