# android build environment

FROM ubuntu:18.04
USER root
# Never ask for confirmations
ENV DEBIAN_FRONTEND noninteractive

# Update apt-get & Install packages
RUN apt update && \
    apt install -y openjdk-8-jdk  bash wget unzip && \
    apt clean

# Export JAVA_HOME variable
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
ENV PATH $PATH:$JAVA_HOME/bin

# Install Android SDK
RUN wget -q http://dl.google.com/android/android-sdk_r24.4.1-linux.tgz && \
    tar -xzf android-sdk_r24.4.1-linux.tgz -C /usr/local              && \
    rm android-sdk_r24.4.1-linux.tgz

# Android SDK Environment variables
ENV ANDROID_HOME /usr/local/android-sdk-linux
ENV PATH $PATH:$ANDROID_HOME/tools
ENV PATH $PATH:$ANDROID_HOME/platform-tools
ENV PATH $PATH:$ANDROID_HOME/build-tools/29.0.3

RUN echo yes | android update sdk --no-ui --all --filter platform-tools             && \
    echo yes | android update sdk --no-ui --all --filter build-tools-29.0.3        && \
    echo yes | android update sdk --no-ui --all --filter android-29                 && \
    echo yes | android update sdk --no-ui --all --filter extra-android-m2repository && \
    echo yes | android update sdk --no-ui --all --filter extra-google-m2repository  && \
    echo yes | android update sdk --no-ui --all --filter extra-android-support

RUN echo "sdk.dir=$ANDROID_HOME" > local.properties
