FROM cidana/androidsdk:29
USER root

# Install Android NDK
RUN  apt update && \
     apt install -y make file
RUN cd /usr/local/ && \
    wget -q https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip && \
    chmod a+x android-ndk-r10e-linux-x86_64.zip                                && \
    unzip -q android-ndk-r10e-linux-x86_64.zip                           && \
    rm android-ndk-r10e-linux-x86_64.zip && \
    apt clean

# Android NDK ENV
ENV NDK_HOME /usr/local/android-ndk-r10e
ENV PATH $PATH:$NDK_HOME

