FROM cidana/androidsdk:28.r21d 
# Export GSTREAMER_ROOT_ANDROID variable
ENV GSTREAMER_ROOT_ANDROID /gstreamer
ENV PATH $PATH:$GSTREAMER_ROOT_ANDROID
RUN apt update -qq && \
    apt install -y git && \
    apt -y install g++ && \
    apt -y install build-essential && \
    apt -y install python && \
	apt -y install git && \
	apt install -y ninja-build && \
    apt install -y curl
# Gstreamer add: \\fileserver\RD\ProgramTools\GStreamer	 
COPY gstreamer-1.0-android-universal-1.14.0.tar.bz2 /
RUN mkdir /gstreamer && \
    cd / && \
    tar jxvf gstreamer-1.0-android-universal-1.14.0.tar.bz2 -C /gstreamer && \
# Install gitlab-runner
    curl -L --output /usr/local/bin/gitlab-runner https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64 && \
    chmod +x /usr/local/bin/gitlab-runner && \
    mkdir /gitlab-runner && \
    gitlab-runner install --user=root --working-directory=/gitlab-runner && \
    gitlab-runner start && \
# Install Cmake
    wget https://cmake.org/files/v3.10/cmake-3.10.2.tar.gz && \
    tar -zxvf cmake-3.10.2.tar.gz && \
    cd cmake-3.10.2 && \
    ./configure && \
    make && \
    make install && \
    cmake --version && \
    cd .. && \
    rm cmake-3.10.2.tar.gz && \
    rm -rf cmake-3.10.0-rc1 && \
    apt clean 