FROM ubuntu:18.04

RUN apt-get update && \
    apt install git -y && \
    apt install ansible -y && \
    apt install sshpass && \
    apt install openjdk-8-jre-headless -y && \
    apt install docker.io -y && \
    apt clean